name: Test workflow

on:
  workflow_dispatch:
    inputs: {}

jobs:
  name: Check
  runs-on: ubuntu-latest

  steps:
  - name: debug GITHUB_TOKEN api limit
    shell: bash
    run: |
      curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{inputs.token}}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/rate_limit
  